# Generated by Django 4.2.1 on 2023-06-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0004_flights'),
        ('CustomerApp', '0006_alter_custumer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.custumer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.flights')),
            ],
        ),
    ]
