# Generated by Django 4.2.1 on 2023-06-03 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineApp', '0003_alter_airline_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('landing_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remaining_tickets', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineApp.airline')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='AirlineApp.country')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_country', to='AirlineApp.country')),
            ],
        ),
    ]
